### ISSUE TITLE
how to select multiple columns from different tables with or without alias using anonymous type and also how to select nested type

### ISSUE THREAD

**Issue by mhkhub** [streamx-co/xlinq.live#19]
how to select multiple columns from different tables with or without alias using anonymous type and also how to select nested type

error : cannot convert from 'string' to 'Streamx.Linq.SQL.IAlias'

**Comment by kostat** [comment]
You have multiple examples of `SELECT` statements, see https://try.entitylinq.com/docs/SqlServerTutorial/Select.md or https://try.entitylinq.com/docs/SqlServerTutorial/InnerJoin.md.
If you want to map the result into an anonymous type, you can do something like this:
```cs
var query = DbContext.Set<FullName>()
                .Query((Customers customer, FullName alias) =>
                {
                    var result = SELECT<FullName>(customer.FirstName.@as(alias.FirstName), customer.LastName.@as(alias.LastName));
                    FROM(customer);

                    return result;
                }).
            Select(t => new { FirstName = "Hey: " + t.FirstName, t.LastName } ) ;
```

**Comment by kostat** [comment]
The same can be also performed using LINQ syntax:
```cs
var query = from t in DbContext.Set<FullName>()
                .Query((Customers customer, FullName alias) =>
                {
                    var result = SELECT<FullName>(customer.FirstName.@as(alias.FirstName),
                                                  customer.LastName.@as(alias.LastName));
                    FROM(customer);

                    return result;
                }) 
            select new { FirstName = "Hey: " + t.FirstName, t.LastName };
```

**Comment by kostat** [comment]
If by "select nested type" you mean loading of related data, it should be performed by the dedicated EF method - `Include()`, see 
https://try.entitylinq.com/docs/SakilaHomework/Homework.md
